version: "3"
services:

  todo-db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres_pw
      - POSTGRES_USER=postgres_user
      - POSTGRES_DB=postgres_db

  todo-backend:
      build:
        context: ./backend
      image: d0derich/todo-ss24-backend:latest
      command: sh -c "pnpm dlx prisma migrate dev && pnpm run dev"
      environment:
        - NODE_ENV=production
        - TZ=Europe/Berlin
        - PORT=3001
        - DATABASE_URL=postgresql://postgres_user:postgres_pw@todo-db:5432/postgres_db
      ports:
        - 3001:3001
      depends_on:
        - todo-db

  todo-frontend:
    # The name of the image that will be created when building this container
    build:
      context: ./frontend
    image: disgame/lab:todo-web
    user: "node"
    environment:
      # Internal server error messages will not send stacktrace to the browser in production
      - NODE_ENV=production
      # Sets the timezone of the containers OS
      - TZ=Europe/Berlin
      - API_URL=http://todo-backend:3001
      - ORIGIN=http://127.0.0.1:3000
    # Points to a file with the sensitive environment variables
    ports:
      - 3000:3000
    depends_on:
      - todo-backend
 
    