openapi: 3.0.0
info:
  title: Todo API
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /todos/{todoString}:
    post:
      summary: Create a new todo
      parameters:
        - in: path
          name: todoString
          required: true
          schema:
            type: string
          description: The todo item to be created
      responses:
        '200':
          description: The created todo item
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  todo:
                    type: string
    delete:
      summary: Delete todos by todoString
      parameters:
        - in: path
          name: todoString
          required: true
          schema:
            type: string
          description: The todo item to be deleted
      responses:
        '200':
          description: The result of the delete operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
  /todos:
    get:
      summary: Retrieve all todos
      responses:
        '200':
          description: A list of todos
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
components:
  schemas:
    Todo:
      type: object
      properties:
        id:
          type: integer
        todo:
          type: string
