apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todoui
  template:
    metadata:
      name: todoui
      labels:
        app: todoui
        tier: frontend
    spec:
      containers:
        - name: todoui
          livenessProbe:
              httpGet:
                path: /
                port: 3000
              initialDelaySeconds: 30
              timeoutSeconds: 1
              periodSeconds: 10
              failureThreshold: 3
          ports:
            - containerPort: 3000
          env:
            - name: API_URL
              value: http://todobackend:3001
            # - name: ORIGIN
            #   value: http://localhost:3000
          image: d0derich/todo-ss24-frontend:latest
      restartPolicy: Always
